# Generated by Django 6.0.1 on 2026-01-29 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_date"],
                "verbose_name": "Стаття",
                "verbose_name_plural": "Статті",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категорія", "verbose_name_plural": "Категорії"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="news.category",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(verbose_name="Текст статті"),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="news_images/", verbose_name="Зображення"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата публікації"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, unique=True, verbose_name="URL-адреса"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Назва категорії"),
        ),
    ]
